// <auto-generated />
using System;
using CourseZero.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CourseZero.Migrations.UploadedFile
{
    [DbContext(typeof(UploadedFileContext))]
    partial class UploadedFileContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourseZero.Models.UploadedFile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Binary");

                    b.Property<string>("Course_Prefix");

                    b.Property<int>("DisLikes");

                    b.Property<string>("File_Description")
                        .HasMaxLength(10240);

                    b.Property<string>("File_Name")
                        .HasMaxLength(256);

                    b.Property<string>("File_Typename")
                        .HasMaxLength(10);

                    b.Property<int>("Likes");

                    b.Property<int>("Related_courseID");

                    b.Property<bool>("Stored_Internally");

                    b.Property<DateTime>("Upload_Time");

                    b.Property<int>("Uploader_UserID");

                    b.Property<string>("Words_for_Search");

                    b.HasKey("ID");

                    b.ToTable("UploadedFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
