// <auto-generated />
using System;
using CourseZero.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CourseZero.Migrations.AuthToken
{
    [DbContext(typeof(AuthTokenContext))]
    [Migration("20190202090452_Update3")]
    partial class Update3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourseZero.Models.AuthToken", b =>
                {
                    b.Property<string>("Token")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Last_access_Browser");

                    b.Property<string>("Last_access_Device");

                    b.Property<string>("Last_access_IP");

                    b.Property<string>("Last_access_Location");

                    b.Property<DateTime>("Last_access_Time");

                    b.Property<int>("userID");

                    b.HasKey("Token");

                    b.ToTable("AuthToken");
                });
#pragma warning restore 612, 618
        }
    }
}
